name: My Deploy

on:
  pull_request:
    branches: [ QA ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID_QA }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          
